const projects = [
  {
    name: "Five-hundred-meter Aperture Spherical Radio Telescope （FAST）",
   
    field: "Space and Astronomy / Radio Astronomy",
    location: "Pingtang, Guizhou",
    lat: 25.652,
    lng: 106.856,
  },
  {
    name: "Jiangmen Underground Neutrino Observatory",
    shortName: "JUNO",
    field: "Physics / Neutrino Physics",
    location: "Jiangmen, Guangdong",
    lat: 22.122,
    lng: 112.518,
  },
  {
    name: "Large High Altitude Air Shower Observatory",
    shortName: "LHAASO",
    field: "Particle and Nuclear Physics / Cosmic-Ray and Gamma-Ray Astronomy",
    location: "Daocheng, Sichuan",
    lat: 29.357,
    lng: 100.138,
  },
  {
    name: "ShenGuang-II Laser Facility",
    shortName: "SG-II",
    field: "Materials Science / High-Energy-Density Physics and High-Power Laser Science",
    location: "Jiading, Shanghai",
    lat: 31.376,
    lng: 121.266,
  },
  {
    name: "China Spallation Neutron Source",
    shortName: "CSNS",
    field: "Materials Science",
    location: "Dongguan, Guangdong",
    lat: 22.985,
    lng: 113.744,
  },
  {
    name: "Thorium Molten Salt Reactor",
    shortName: "TMSR",
    field: "Energy",
    location: "Wuwei, Gansu",
    lat: 37.928,
    lng: 102.638,
  },
  {
    name: "CHIEF1300",
    shortName: "CHIEF1300",
    field: "Engineering and Technology / Hypergravity Science",
    location: "Hangzhou, Zhejiang",
    lat: 30.308,
    lng: 120.086,
  },
  {
    name: "Centrifugal Hypergravity and Interdisciplinary Experiment Facility",
    shortName: "CHIEF",
    field: "Engineering and Technology / Hypergravity and Interdisciplinary Experiment Science",
    location: "Hangzhou, Zhejiang",
    lat: 30.308,
    lng: 120.086,
  },
  {
    name: "Burning Plasma Experimental Superconducting Tokamak",
    shortName: "BEST",
    field: "Energy",
    location: "Hefei, Anhui",
    lat: 31.822,
    lng: 117.271,
  },
  {
    name: "Beijing Electron Positron Collider II",
    shortName: "BEPCII",
    field: "Particle and Nuclear Physics / Tau-Charm Collider Physics",
    location: "Shijingshan, Beijing",
    lat: 39.914,
    lng: 116.24,
  },
  {
    name: "Shanghai Synchrotron Radiation Facility",
    shortName: "SSRF",
    field: "Materials Science / Synchrotron Radiation and Photon Science",
    location: "Pudong, Shanghai",
    lat: 31.19,
    lng: 121.594,
  },
  {
    name: "Shanghai Hard X-ray Free Electron Laser Facility",
    shortName: "SHINE",
    field: "Materials Science / Hard X-ray Free-Electron Laser and Photon Science",
    location: "Pudong, Shanghai",
    lat: 31.19,
    lng: 121.594,
  },
  {
    name: "Dalian Coherent Light Source",
    shortName: "DCLS",
    field: "Materials Science / Extreme Ultraviolet Free-Electron Laser Science",
    location: "Dalian, Liaoning",
    lat: 39.235,
    lng: 121.71,
  },
  {
    name: "Experimental Advanced Superconducting Tokamak",
    shortName: "EAST",
    field: "Energy / Magnetic-Confinement Fusion",
    location: "Hefei, Anhui",
    lat: 31.822,
    lng: 117.271,
  },
  {
    name: "China National GeneBank",
    shortName: "CNGB",
    field: "Biology / Genomics and Bioresource Preservation",
    location: "Shenzhen, Guangdong",
    lat: 22.599,
    lng: 114.543,
  },
  {
    name: "China Remote Sensing Satellite Ground Station",
    shortName: "RSGS",
    field: "Earth System and Environment / Satellite Data Reception and Remote Sensing",
    location: "Beijing Headquarters",
    lat: 40.074,
    lng: 116.287,
  },
  {
    name: "Heavy Ion Research Facility Lanzhou",
    shortName: "HIRFL",
    field: "Particle and Nuclear Physics / Heavy-Ion Accelerator and Nuclear Physics",
    location: "Lanzhou, Gansu",
    lat: 36.061,
    lng: 103.834,
  },
  {
    name: "High Intensity Heavy Ion Accelerator Facility",
    shortName: "HIAF",
    field: "Particle and Nuclear Physics / Heavy-Ion Accelerator and Nuclear Science",
    location: "Huizhou, Guangdong",
    lat: 23.111,
    lng: 114.416,
  },
  {
    name: "National Synchrotron Radiation Laboratory",
    shortName: "NSRL",
    field: "Materials Science / Vacuum Ultraviolet and Soft X-ray Synchrotron Radiation",
    location: "Hefei, Anhui",
    lat: 31.838,
    lng: 117.253,
  },
  {
    name: "Steady High Magnetic Field Facility",
    shortName: "SHMFF",
    field: "Materials Science / High Magnetic Field Science",
    location: "Hefei, Anhui",
    lat: 31.839,
    lng: 117.257,
  },
  {
    name: "Shanghai Soft X-ray Free Electron Laser Facility",
    shortName: "SXFEL",
    field: "Materials Science / Soft X-ray Free-Electron Laser",
    location: "Pudong, Shanghai",
    lat: 31.19,
    lng: 121.594,
  },
  {
    name: "Synergetic Extreme Condition User Facility",
    shortName: "SECUF",
    field: "Materials Science / Extreme Conditions Materials Science",
    location: "Huairou, Beijing",
    lat: 40.315,
    lng: 116.631,
  },
  {
    name: "High Energy Photon Source",
    shortName: "HEPS",
    field: "Materials Science / High-Energy Synchrotron Radiation and Photon Science",
    location: "Huairou, Beijing",
    lat: 40.323,
    lng: 116.637,
  },
  {
    name: "National Biosafety Laboratory",
    shortName: "NBL",
    field: "Biology / Biosafety and Virology",
    location: "Wuhan, Hubei",
    lat: 30.546,
    lng: 114.362,
  },
  {
    name: "Large Sky Area Multi-Object Fiber Spectroscopic Telescope",
    shortName: "LAMOST",
    field: "Space and Astronomy / Optical Spectroscopy and Survey Astronomy",
    location: "Xinglong, Hebei",
    lat: 40.393,
    lng: 117.584,
  },
  {
    name: "National Facility for Protein Science in Shanghai",
    shortName: "NFPS",
    field: "Biology / Protein Science and Structural Biology",
    location: "Pudong, Shanghai",
    lat: 31.192,
    lng: 121.602,
  },
  {
    name: "National Research Facility for Phenotypic and Genetic Analysis of Model Animals (Primate Facility)",
    shortName: "MAF",
    field: "Biology / Primate Model Animal Phenotyping and Genetics",
    location: "Kunming, Yunnan",
    lat: 25.04,
    lng: 102.649,
  },
  {
    name: "Earth System Numerical Simulation Facility",
    shortName: "EarthLab",
    field: "Earth System and Environment / Earth System Numerical Modeling",
    location: "Miyun, Beijing",
    lat: 40.011,
    lng: 116.407,
  },
  {
    name: "Comprehensive Research Facility for Fusion Technology",
    shortName: "CRAFT",
    field: "Energy / Fusion Technology and Reactor Key Systems",
    location: "Hefei, Anhui",
    lat: 31.884,
    lng: 117.258,
  },
  {
    name: "Chinese Meridian Project (Phase I & II)",
    shortName: "MSP",
    field: "Space and Astronomy / Space Weather and Geospace Monitoring",
    location: "Beijing Headquarters",
    lat: 39.982,
    lng: 116.318,
  },
  {
    name: "Multi-Purpose Oceanographic Research Vessel",
    shortName: "MORV",
    field: "Earth System and Environment / Oceanography and Marine Survey",
    location: "Qingdao, Shandong",
    lat: 35.96,
    lng: 120.19,
  },
  {
    name: "Chinese Aeronautic Remote Sensing System (including Remote Sensing Aircraft)",
    shortName: "CARSS",
    field: "Earth System and Environment / Airborne Remote Sensing",
    location: "Beijing",
    lat: 40.074,
    lng: 116.287,
  },
  {
    name: "BPL and BPM Time Service Systems",
    shortName: "BPL.BPM",
    field: "Engineering and Technology / Time-Frequency Metrology and Time Service",
    location: "Xi'an, Shaanxi",
    lat: 34.371,
    lng: 109.215,
  },
  {
    name: "The Germplasm Bank of Wild Species",
    shortName: "GBOWS",
    field: "Biology / Biodiversity Conservation and Germplasm Preservation",
    location: "Kunming, Yunnan",
    lat: 25.041,
    lng: 102.744,
  },
  {
    name: "Shiyan 1 Research Vessel",
    shortName: "Shiyan1",
    field: "Earth System and Environment / Marine Acoustics and Multidisciplinary Ocean Experiments",
    location: "Guangzhou, Guangdong",
    lat: 23.097,
    lng: 113.298,
  },
  {
    name: "HOV and Research Vessel",
    shortName: "HOV",
    field: "Earth System and Environment / Deep-Sea Crewed Submersible Operations",
    location: "Sanya, Hainan",
    lat: 18.223,
    lng: 109.508,
  },
  {
    name: "National Major Science and Technology Infrastructure for Translational Medicine",
    shortName: "TransMed",
    field: "Biomedical Research / Translational Medicine",
    coordinateType: "multi-site",
    
    coordinates: {
      lat: 35.0,
      lng: 104.0,
    },
    sites: [
      {
        siteName: "Shanghai",
        host: "Shanghai Jiao Tong University / Ruijin Hospital",
        location: "Shanghai",
        lat: 31.2304,
        lng: 121.4737,
      },
      {
        siteName: "Sichuan",
        host: "Sichuan University / West China Hospital",
        location: "Chengdu, Sichuan",
        lat: 30.641,
        lng: 104.066,
      },
      {
        siteName: "Beijing (PUMCH)",
        host: "Peking Union Medical College Hospital",
        location: "Dongcheng District, Beijing",
        lat: 39.908,
        lng: 116.418,
      },
      {
        siteName: "Beijing (PLAGH)",
        host: "Chinese PLA General Hospital",
        location: "Beijing",
        lat: 39.907,
        lng: 116.281,
      },
      {
        siteName: "Xi'an",
        host: "Air Force Medical University",
        location: "Xi'an, Shaanxi",
        lat: 34.265,
        lng: 108.96,
      },
    ],
  },
];
